version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: midterm
      MYSQL_USER: admin1
      MYSQL_PASSWORD: welcome1
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  haproxy:
    image: eeacms/haproxy
    depends_on: [cashier1,cashier2]
      # - cashier2
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      #- "8080:5000"
      - "8081:1936"
      - "9090:9090"
    #environment:
    #  BACKENDS: "cashier1"
      

  cashier1:
    image: spring-cashier
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/midterm
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: welcome
    # deploy:
    #   replicas: 2
    depends_on:
      - db
    #ports:
    #  - 9000:9090

  cashier2:
    image: spring-cashier
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/midterm
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: welcome
    # deploy:
    #   replicas: 2
    depends_on:
      - db
    #ports:
    #  - 9001:9090

volumes:
  db_data:
